import type { ApiEndpoint } from './index';

export const accordEndpoints: ApiEndpoint[] = [
  {
    path: '/api/accords',
    group: 'accords',
    methods: [
      {
        method: 'GET',
        summary: 'List accords with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by title or description' },
          { name: 'status', type: 'string', required: false, description: 'Filter: lead, meeting, proposal, contract, signed, active, lost' },
          { name: 'owner_id', type: 'uuid', required: false, description: 'Filter by owner user ID' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Filter by client ID' },
          { name: 'page', type: 'number', required: false, description: 'Page number (default 1)' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page (default 50)' },
        ],
        responseExample: {
          accords: [{
            id: 'uuid',
            title: 'string',
            status: 'lead|meeting|proposal|contract|signed|active|lost',
            owner_id: 'uuid',
            client_id: 'uuid|null',
            total_value: 'number|null',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
      },
      {
        method: 'POST',
        summary: 'Create a new accord.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'title', type: 'string', required: true, description: 'Accord title' },
          { name: 'status', type: 'string', required: false, description: 'Initial status (default: lead)' },
          { name: 'owner_id', type: 'uuid', required: true, description: 'Owner user ID' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Associated client ID' },
          { name: 'description', type: 'string', required: false, description: 'Description or notes' },
        ],
        responseExample: {
          id: 'uuid',
          title: 'string',
          status: 'string',
          owner_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/accords/:id',
    group: 'accords',
    methods: [
      {
        method: 'GET',
        summary: 'Get accord details with charter_items, commission_items, and keep_items.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          title: 'string',
          status: 'string',
          owner_id: 'uuid',
          client_id: 'uuid|null',
          description: 'string|null',
          total_value: 'number|null',
          charter_items: [{ id: 'uuid', ware_id: 'uuid', final_price: 'number', billing_period: 'string' }],
          commission_items: [{ id: 'uuid', ware_id: 'uuid', final_price: 'number|null' }],
          keep_items: [{ id: 'uuid', monthly_total: 'number|null' }],
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update an accord.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'title', type: 'string', required: false, description: 'Accord title' },
          { name: 'owner_id', type: 'uuid', required: false, description: 'Owner user ID' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Associated client ID' },
          { name: 'description', type: 'string', required: false, description: 'Description or notes' },
        ],
        responseExample: {
          id: 'uuid',
          title: 'string',
          status: 'string',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete an accord.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/accords/:id/status',
    group: 'accords',
    methods: [
      {
        method: 'PATCH',
        summary: 'Transition accord status.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'status', type: 'string', required: true, description: 'New status: lead, meeting, proposal, contract, signed, active, lost' },
          { name: 'rejection_reason', type: 'string', required: false, description: 'Reason when transitioning to lost' },
        ],
        responseExample: {
          id: 'uuid',
          status: 'string',
          updated_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/accords/:id/charter-items',
    group: 'accords',
    methods: [
      {
        method: 'GET',
        summary: 'List charter items for an accord.',
        auth: 'required',
        responseExample: [{
          id: 'uuid',
          accord_id: 'uuid',
          ware_id: 'uuid',
          base_price: 'number',
          final_price: 'number',
          billing_period: 'monthly|annually',
          duration_months: 'number',
          total_contract_value: 'number',
        }],
      },
      {
        method: 'POST',
        summary: 'Add a charter item to an accord.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'ware_id', type: 'uuid', required: true, description: 'Charter-type ware ID' },
          { name: 'base_price', type: 'number', required: true, description: 'Base price before discount' },
          { name: 'billing_period', type: 'string', required: true, description: 'monthly or annually' },
          { name: 'duration_months', type: 'number', required: true, description: 'Commitment length in months' },
          { name: 'discount_type', type: 'string', required: false, description: 'percent or flat' },
          { name: 'discount_value', type: 'number', required: false, description: 'Discount amount' },
          { name: 'name_override', type: 'string', required: false, description: 'Custom name' },
          { name: 'price_tier', type: 'string', required: false, description: 'Selected tier name' },
        ],
        responseExample: {
          id: 'uuid',
          accord_id: 'uuid',
          final_price: 'number',
          total_contract_value: 'number',
        },
      },
    ],
  },
  {
    path: '/api/accords/:id/charter-items/:itemId',
    group: 'accords',
    methods: [
      {
        method: 'PATCH',
        summary: 'Update a charter item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'base_price', type: 'number', required: false, description: 'Base price' },
          { name: 'discount_type', type: 'string', required: false, description: 'percent or flat' },
          { name: 'discount_value', type: 'number', required: false, description: 'Discount amount' },
          { name: 'billing_period', type: 'string', required: false, description: 'monthly or annually' },
          { name: 'duration_months', type: 'number', required: false, description: 'Commitment length' },
        ],
        responseExample: { id: 'uuid', final_price: 'number', total_contract_value: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a charter item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/accords/:id/commission-items',
    group: 'accords',
    methods: [
      {
        method: 'GET',
        summary: 'List commission items for an accord.',
        auth: 'required',
        responseExample: [{
          id: 'uuid',
          accord_id: 'uuid',
          ware_id: 'uuid',
          estimated_price: 'number|null',
          final_price: 'number|null',
          project_id: 'uuid|null',
        }],
      },
      {
        method: 'POST',
        summary: 'Add a commission item to an accord.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'ware_id', type: 'uuid', required: true, description: 'Commission-type ware ID' },
          { name: 'estimated_price', type: 'number', required: false, description: 'Rough price estimate' },
          { name: 'project_id', type: 'uuid', required: false, description: 'Linked project ID' },
          { name: 'discount_type', type: 'string', required: false, description: 'percent or flat' },
          { name: 'discount_value', type: 'number', required: false, description: 'Discount amount' },
        ],
        responseExample: { id: 'uuid', final_price: 'number|null' },
      },
    ],
  },
  {
    path: '/api/accords/:id/commission-items/:itemId',
    group: 'accords',
    methods: [
      {
        method: 'PATCH',
        summary: 'Update a commission item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'estimated_price', type: 'number', required: false, description: 'Estimated price' },
          { name: 'project_id', type: 'uuid', required: false, description: 'Link/change project' },
          { name: 'discount_type', type: 'string', required: false, description: 'percent or flat' },
          { name: 'discount_value', type: 'number', required: false, description: 'Discount amount' },
        ],
        responseExample: { id: 'uuid', final_price: 'number|null' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a commission item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/accords/:id/keep-items',
    group: 'accords',
    methods: [
      {
        method: 'GET',
        summary: 'List keep items for an accord.',
        auth: 'required',
        responseExample: [{
          id: 'uuid',
          accord_id: 'uuid',
          site_id: 'uuid|null',
          hosting_final_price: 'number|null',
          maintenance_final_price: 'number|null',
          monthly_total: 'number|null',
        }],
      },
      {
        method: 'POST',
        summary: 'Add a keep item to an accord.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'maintenance_plan_id', type: 'uuid', required: true, description: 'Maintenance plan ID' },
          { name: 'maintenance_price', type: 'number', required: true, description: 'Maintenance base price' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Linked site ID' },
          { name: 'hosting_plan_id', type: 'uuid', required: false, description: 'Hosting plan ID' },
          { name: 'hosting_price', type: 'number', required: false, description: 'Hosting base price' },
          { name: 'is_client_hosted', type: 'boolean', required: false, description: 'Whether client hosts the site' },
        ],
        responseExample: { id: 'uuid', monthly_total: 'number' },
      },
    ],
  },
  {
    path: '/api/accords/:id/keep-items/:itemId',
    group: 'accords',
    methods: [
      {
        method: 'PATCH',
        summary: 'Update a keep item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'hosting_price', type: 'number', required: false, description: 'Hosting price' },
          { name: 'maintenance_price', type: 'number', required: false, description: 'Maintenance price' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Link/change site' },
          { name: 'is_client_hosted', type: 'boolean', required: false, description: 'Client hosted flag' },
        ],
        responseExample: { id: 'uuid', monthly_total: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a keep item.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
];
