import type { ApiEndpoint } from './index';

export const automationEndpoints: ApiEndpoint[] = [
  {
    path: '/api/sales-automation-rules',
    group: 'automation',
    methods: [
      {
        method: 'GET',
        summary: 'List all automation rules.',
        auth: 'required',
        responseExample: {
          rules: [{
            id: 'uuid',
            name: 'string',
            trigger_type: 'string',
            trigger_status: 'string|null',
            trigger_from_status: 'string|null',
            time_threshold_hours: 'number|null',
            action_type: 'string',
            task_template: 'object|null',
            assignee_rule: 'string|null',
            assignee_user_id: 'uuid|null',
            is_active: 'boolean',
            sort_order: 'number',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
        },
      },
      {
        method: 'POST',
        summary: 'Create a new automation rule.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: true, description: 'Rule name' },
          { name: 'trigger_type', type: 'string', required: true, description: 'Trigger type' },
          { name: 'trigger_status', type: 'string', required: false, description: 'Status that triggers the rule' },
          { name: 'trigger_from_status', type: 'string', required: false, description: 'Previous status for transition triggers' },
          { name: 'time_threshold_hours', type: 'number', required: false, description: 'Hours threshold for time-based triggers' },
          { name: 'action_type', type: 'string', required: true, description: 'Action to perform when triggered' },
          { name: 'task_template', type: 'object', required: false, description: 'Task template for task creation actions' },
          { name: 'assignee_rule', type: 'string', required: false, description: 'Rule for assigning tasks' },
          { name: 'assignee_user_id', type: 'uuid', required: false, description: 'Specific user to assign tasks to' },
          { name: 'is_active', type: 'boolean', required: false, description: 'Whether the rule is active (default true)' },
          { name: 'sort_order', type: 'number', required: false, description: 'Sort order for rule evaluation' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          trigger_type: 'string',
          action_type: 'string',
          is_active: 'boolean',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/sales-automation-rules/:id',
    group: 'automation',
    methods: [
      {
        method: 'GET',
        summary: 'Get a single automation rule.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          trigger_type: 'string',
          trigger_status: 'string|null',
          trigger_from_status: 'string|null',
          time_threshold_hours: 'number|null',
          action_type: 'string',
          task_template: 'object|null',
          assignee_rule: 'string|null',
          assignee_user_id: 'uuid|null',
          is_active: 'boolean',
          sort_order: 'number',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update an automation rule.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: false, description: 'Rule name' },
          { name: 'trigger_type', type: 'string', required: false, description: 'Trigger type' },
          { name: 'trigger_status', type: 'string', required: false, description: 'Status that triggers the rule' },
          { name: 'trigger_from_status', type: 'string', required: false, description: 'Previous status for transition triggers' },
          { name: 'time_threshold_hours', type: 'number', required: false, description: 'Hours threshold for time-based triggers' },
          { name: 'action_type', type: 'string', required: false, description: 'Action to perform when triggered' },
          { name: 'task_template', type: 'object', required: false, description: 'Task template for task creation actions' },
          { name: 'assignee_rule', type: 'string', required: false, description: 'Rule for assigning tasks' },
          { name: 'assignee_user_id', type: 'uuid', required: false, description: 'Specific user to assign tasks to' },
          { name: 'is_active', type: 'boolean', required: false, description: 'Whether the rule is active' },
          { name: 'sort_order', type: 'number', required: false, description: 'Sort order for rule evaluation' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          is_active: 'boolean',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'DELETE',
        summary: 'Delete an automation rule.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/cron/sales-automation',
    group: 'automation',
    methods: [
      {
        method: 'POST',
        summary: 'Evaluate time-based automation rules.',
        auth: 'cron',
        responseExample: {
          evaluated: 'number',
          triggered: 'number',
        },
      },
    ],
  },
  {
    path: '/api/projects/:id/scope-check',
    group: 'automation',
    methods: [
      {
        method: 'POST',
        summary: 'Check scope_locked status for a project.',
        auth: 'required',
        responseExample: {
          scope_locked: 'boolean',
          project_id: 'uuid',
        },
      },
    ],
  },
];
