import type { ApiEndpoint } from './index';

export const clientEndpoints: ApiEndpoint[] = [
  {
    path: '/api/clients',
    group: 'clients',
    methods: [
      {
        method: 'GET',
        summary: 'List clients with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'status', type: 'string', required: false, description: 'Filter: active, inactive, delinquent' },
          { name: 'type', type: 'string', required: false, description: 'Filter: direct, agency_partner, sub_client' },
          { name: 'page', type: 'number', required: false, description: 'Page number (default 1)' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page (default 50)' },
        ],
        responseExample: {
          clients: [{
            id: 'uuid',
            name: 'string',
            type: 'direct|agency_partner|sub_client',
            status: 'active|inactive|delinquent',
            primary_contact: 'string|null',
            email: 'string|null',
            phone: 'string|null',
            retainer_hours: 'number|null',
            hourly_rate: 'number|null',
            retainer_usage_mode: 'string|null',
            parent_agency_id: 'uuid|null',
            parent_agency: 'object|null',
            notes: 'string|null',
            sites_count: 'number',
            sub_clients_count: 'number',
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
        responseNotes: 'List response does not include nested sites or sub_clients arrays. Use GET /api/clients/:id for full detail.',
      },
      {
        method: 'POST',
        summary: 'Create a new client.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: true, description: 'Client name' },
          { name: 'type', type: 'string', required: false, description: 'direct, agency_partner, sub_client' },
          { name: 'status', type: 'string', required: false, description: 'active, inactive, delinquent' },
          { name: 'primary_contact', type: 'string', required: false, description: 'Contact name' },
          { name: 'email', type: 'string', required: false, description: 'Contact email' },
          { name: 'phone', type: 'string', required: false, description: 'Contact phone' },
          { name: 'retainer_hours', type: 'number', required: false, description: 'Monthly retainer hours' },
          { name: 'hourly_rate', type: 'number', required: false, description: 'Hourly rate' },
          { name: 'parent_agency_id', type: 'uuid', required: false, description: 'Parent agency client ID' },
          { name: 'notes', type: 'string', required: false, description: 'Notes' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          type: 'string',
          status: 'string',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/clients/:id',
    group: 'clients',
    methods: [
      {
        method: 'GET',
        summary: 'Get client details including sites and sub-clients.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          type: 'string',
          status: 'string',
          primary_contact: 'string|null',
          email: 'string|null',
          phone: 'string|null',
          retainer_hours: 'number|null',
          hourly_rate: 'number|null',
          retainer_usage_mode: 'string|null',
          parent_agency_id: 'uuid|null',
          parent_agency: 'object|null',
          notes: 'string|null',
          sites_count: 'number',
          sub_clients_count: 'number',
          sites: [{ id: 'uuid', name: 'string', url: 'string|null' }],
          sub_clients: [{ id: 'uuid', name: 'string' }],
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a client.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: false, description: 'Client name' },
          { name: 'status', type: 'string', required: false, description: 'active, inactive, delinquent' },
          { name: 'type', type: 'string', required: false, description: 'direct, agency_partner, sub_client' },
          { name: 'primary_contact', type: 'string', required: false, description: 'Contact name' },
          { name: 'email', type: 'string', required: false, description: 'Contact email' },
          { name: 'phone', type: 'string', required: false, description: 'Contact phone' },
          { name: 'retainer_hours', type: 'number', required: false, description: 'Monthly retainer hours' },
          { name: 'hourly_rate', type: 'number', required: false, description: 'Hourly rate' },
          { name: 'notes', type: 'string', required: false, description: 'Notes' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          status: 'string',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a client.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/clients/:id/activity',
    group: 'clients',
    methods: [
      {
        method: 'GET',
        summary: 'Get client activity — projects, tasks, and time entries.',
        auth: 'required',
        queryParams: [
          { name: 'projectStatus', type: 'string', required: false, description: 'Filter by project status' },
          { name: 'taskType', type: 'string', required: false, description: 'Filter task type' },
          { name: 'taskStatus', type: 'string', required: false, description: 'Filter task status' },
        ],
        responseExample: {
          projects: [{ id: 'uuid', name: 'string', status: 'string', tasks_count: 'number' }],
          tasks: [{ id: 'uuid', title: 'string', status: 'string' }],
          time_entries: [{ id: 'uuid', duration: 'number', started_at: 'ISO-8601' }],
        },
      },
    ],
  },
  {
    path: '/api/clients/:id/retainer',
    group: 'clients',
    methods: [
      {
        method: 'GET',
        summary: 'Get client retainer usage for a specific month.',
        auth: 'required',
        queryParams: [
          { name: 'month', type: 'string', required: false, description: 'Month in YYYY-MM format (defaults to current)' },
        ],
        responseExample: {
          retainer_hours: 'number',
          hours_used: 'number',
          hours_remaining: 'number',
          usage_percent: 'number',
          entries: [{ id: 'uuid', duration: 'number', task: { id: 'uuid', title: 'string' } }],
        },
      },
      {
        method: 'PATCH',
        summary: 'Update retainer configuration.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/clients/bulk',
    group: 'clients',
    methods: [
      {
        method: 'PATCH',
        summary: 'Bulk update clients.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true, count: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Bulk soft delete clients.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true, count: 'number' },
      },
    ],
  },
];
