import type { ApiEndpoint } from './index';

export const projectEndpoints: ApiEndpoint[] = [
  {
    path: '/api/projects',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'List projects with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'status', type: 'string', required: false, description: 'Filter by single status' },
          { name: 'statuses', type: 'string', required: false, description: 'Comma-separated status list' },
          { name: 'type', type: 'string', required: false, description: 'project, retainer, internal' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Filter by client' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Filter by site' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          projects: [{
            id: 'uuid',
            name: 'string',
            description: 'string|null',
            status: 'quote|queue|ready|in_progress|review|done|suspended|cancelled',
            type: 'project|retainer|internal',
            client_id: 'uuid',
            client: { id: 'uuid', name: 'string', status: 'string' },
            site: { id: 'uuid', name: 'string', url: 'string|null' },
            start_date: 'ISO-8601|null',
            target_date: 'ISO-8601|null',
            billing_type: 'fixed|hourly|retainer|none',
            budget_locked: 'boolean',
            calculated: {
              estimated_hours_min: 'number',
              estimated_hours_max: 'number',
              estimated_range: 'string',
              time_spent_minutes: 'number',
              task_count: 'number',
              completed_task_count: 'number',
              progress_percent: 'number',
            },
            tasks_count: 'number',
            health: 'object|null',
            created_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
        responseNotes: 'List response excludes nested tasks, phases, team_assignments, and milestones. Use GET /api/projects/:id for full detail. health is null for non-active projects.',
      },
      {
        method: 'POST',
        summary: 'Create a new project.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: true, description: 'Project name' },
          { name: 'client_id', type: 'uuid', required: true, description: 'Client ID' },
          { name: 'description', type: 'string', required: false, description: 'Project description' },
          { name: 'status', type: 'string', required: false, description: 'Initial status' },
          { name: 'type', type: 'string', required: false, description: 'project, retainer, internal' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Associated site' },
          { name: 'recipe_id', type: 'uuid', required: false, description: 'Recipe template to use' },
          { name: 'start_date', type: 'ISO-8601', required: false, description: 'Start date' },
          { name: 'target_date', type: 'ISO-8601', required: false, description: 'Target completion date' },
          { name: 'billing_type', type: 'string', required: false, description: 'fixed, hourly, retainer, none' },
          { name: 'hourly_rate', type: 'number', required: false, description: 'Hourly rate for billing' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          status: 'string',
          client_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/projects/:id',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'Get project details with tasks, phases, team, milestones, and calculated budget.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          description: 'string|null',
          status: 'string',
          type: 'string',
          client_id: 'uuid',
          client: { id: 'uuid', name: 'string', status: 'string' },
          site: { id: 'uuid', name: 'string', url: 'string|null' },
          start_date: 'ISO-8601|null',
          target_date: 'ISO-8601|null',
          completed_date: 'ISO-8601|null',
          billing_type: 'string',
          budget_hours: 'number|null',
          hourly_rate: 'number|null',
          budget_amount: 'number|null',
          budget_locked: 'boolean',
          budget_locked_at: 'ISO-8601|null',
          is_retainer: 'boolean',
          calculated: {
            estimated_hours_min: 'number',
            estimated_hours_max: 'number',
            estimated_range: 'string',
            time_spent_minutes: 'number',
            task_count: 'number',
            completed_task_count: 'number',
            total_energy_minutes: 'number',
            completed_energy_minutes: 'number',
            progress_percent: 'number',
          },
          phases: [{ id: 'uuid', name: 'string', icon: 'string|null', sort_order: 'number' }],
          tasks: [{ id: 'uuid', title: 'string', status: 'string', priority: 'number' }],
          team_assignments: [{ id: 'uuid', user: { id: 'uuid', name: 'string' }, is_lead: 'boolean' }],
          milestones: [{ id: 'uuid', name: 'string', target_date: 'ISO-8601|null', billing_status: 'string' }],
          health: 'object|null',
          tasks_count: 'number',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
        responseNotes: 'health is null for non-active projects (only calculated for ready, in_progress, review). Tasks in the detail view include full formatTaskResponse shape.',
      },
      {
        method: 'PATCH',
        summary: 'Update project fields or lock budget.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: {
          id: 'uuid',
          name: 'string',
          status: 'string',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a project.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/projects/:id/milestones',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'List milestones for a project.',
        auth: 'required',
        responseExample: {
          milestones: [{
            id: 'uuid',
            name: 'string',
            project_id: 'uuid',
            phase_id: 'uuid|null',
            target_date: 'ISO-8601|null',
            completed_at: 'ISO-8601|null',
            notes: 'string|null',
            sort_order: 'number',
            billing_amount: 'number|null',
            billing_status: 'string',
            triggered_at: 'ISO-8601|null',
            invoiced_at: 'ISO-8601|null',
            created_at: 'ISO-8601',
          }],
        },
      },
      {
        method: 'POST',
        summary: 'Create a milestone.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: true, description: 'Milestone name' },
          { name: 'phase_id', type: 'uuid', required: false, description: 'Optional phase link' },
          { name: 'target_date', type: 'ISO-8601', required: false, description: 'Target date' },
          { name: 'billing_amount', type: 'number', required: false, description: 'Billing amount' },
          { name: 'notes', type: 'string', required: false, description: 'Notes' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          project_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/projects/:id/phases',
    group: 'projects',
    methods: [
      {
        method: 'POST',
        summary: 'Create a project phase.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', sort_order: 'number' },
      },
      {
        method: 'PATCH',
        summary: 'Update or reorder phases.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
      {
        method: 'DELETE',
        summary: 'Delete a phase.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/projects/:id/tasks/reorder',
    group: 'projects',
    methods: [
      {
        method: 'PATCH',
        summary: 'Reorder tasks within phases.',
        auth: 'required',
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/projects/:id/team',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'Get project team assignments.',
        auth: 'required',
        responseExample: {
          team: [{
            id: 'uuid',
            project_id: 'uuid',
            user_id: 'uuid',
            user: { id: 'uuid', name: 'string', email: 'string' },
            function: { id: 'uuid', name: 'string' },
            is_lead: 'boolean',
            created_at: 'ISO-8601',
          }],
        },
      },
      {
        method: 'POST',
        summary: 'Add team member to project.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', user_id: 'uuid', is_lead: 'boolean' },
      },
      {
        method: 'PATCH',
        summary: 'Update team assignment.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
      {
        method: 'DELETE',
        summary: 'Remove team member from project.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/projects/:id/resource-links',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'List project resource links (Figma, Drive, etc).',
        auth: 'required',
        responseExample: {
          links: [{ id: 'uuid', title: 'string', url: 'string', type: 'string|null', created_at: 'ISO-8601' }],
        },
      },
      {
        method: 'POST',
        summary: 'Add a resource link to a project.',
        auth: 'required',
        responseExample: { id: 'uuid', title: 'string', url: 'string' },
      },
    ],
  },
  {
    path: '/api/milestones/:id',
    group: 'projects',
    methods: [
      {
        method: 'GET',
        summary: 'Get a milestone.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          project_id: 'uuid',
          phase_id: 'uuid|null',
          target_date: 'ISO-8601|null',
          completed_at: 'ISO-8601|null',
          notes: 'string|null',
          sort_order: 'number',
          billing_amount: 'number|null',
          billing_status: 'string',
          triggered_at: 'ISO-8601|null',
          triggered_by_id: 'uuid|null',
          invoiced_at: 'ISO-8601|null',
          invoiced_by_id: 'uuid|null',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a milestone.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', updated_at: 'ISO-8601' },
      },
      {
        method: 'DELETE',
        summary: 'Delete a milestone.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/milestones/:id/trigger',
    group: 'projects',
    methods: [
      {
        method: 'POST',
        summary: 'Trigger milestone billing (mark as ready to invoice).',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true, billing_status: 'triggered' },
      },
    ],
  },
  {
    path: '/api/milestones/:id/invoice',
    group: 'projects',
    methods: [
      {
        method: 'POST',
        summary: 'Mark a milestone as invoiced.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true, billing_status: 'invoiced' },
      },
    ],
  },
  {
    path: '/api/projects/wizard',
    group: 'projects',
    methods: [
      {
        method: 'POST',
        summary: 'Create a project from a recipe template with phases and tasks.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: {
          id: 'uuid',
          name: 'string',
          phases_created: 'number',
          tasks_created: 'number',
        },
        responseNotes: 'Creates project, copies phases and tasks from the referenced recipe template. Returns counts of created entities.',
      },
    ],
  },
];
