import type { ApiEndpoint } from './index';

export const siteEndpoints: ApiEndpoint[] = [
  {
    path: '/api/sites',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'List sites with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Filter by client' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          sites: [{
            id: 'uuid',
            name: 'string',
            url: 'string|null',
            client_id: 'uuid',
            client: { id: 'uuid', name: 'string' },
            hosted_by: 'string|null',
            platform: 'string|null',
            hosting_plan: { id: 'uuid', name: 'string', rate: 'number' },
            hosting_discount: 'number|null',
            maintenance_plan: { id: 'uuid', name: 'string', rate: 'number', frequency: 'string' },
            maintenance_assignee: { id: 'uuid', name: 'string', email: 'string' },
            domains_count: 'number',
            primary_domain: { id: 'uuid', name: 'string', is_primary: true },
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
      },
      {
        method: 'POST',
        summary: 'Create a new site. Accepts repo + staging/Bast config so a site can be created with its repo in one call.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: true, description: 'Site name' },
          { name: 'client_id', type: 'uuid', required: true, description: 'Owning client' },
          { name: 'url', type: 'string', required: false, description: 'Production URL' },
          { name: 'hosted_by', type: 'string', required: false, description: 'indelible | client | other (default indelible)' },
          { name: 'platform', type: 'string', required: false, description: 'Hosting platform' },
          { name: 'site_type', type: 'string', required: false, description: 'eleventy | wordpress | handoff | custom' },
          { name: 'repo_url', type: 'string', required: false, description: 'Eleventy: git repo URL' },
          { name: 'repo_branch', type: 'string', required: false, description: 'Eleventy: branch' },
          { name: 'prod_branch', type: 'string', required: false, description: 'Bast: production deploy branch (else repo_branch is treated as prod)' },
          { name: 'staging_branch', type: 'string', required: false, description: 'Bast: staging deploy branch (default convention: staging)' },
          { name: 'staging_url', type: 'string', required: false, description: 'Bast: staging preview URL (default convention: staging.{primary-domain})' },
          { name: 'staging_auth_user', type: 'string', required: false, description: 'Bast: staging basic-auth user (keeps bots/Google out; not real security)' },
          { name: 'staging_auth_password', type: 'string', required: false, description: 'Bast: staging basic-auth password (stored plain by design)' },
          { name: 'bast_enabled', type: 'boolean', required: false, description: 'Capability gate: Bast is turned on for THIS site (default false). AND-ed with Sop.bast_executable.' },
          { name: 'auto_deploy', type: 'boolean', required: false, description: 'true = Bast pushes straight to prod_branch; false = stage to staging_branch for client approval.' },
        ],
        responseExample: {
          id: 'uuid',
          name: 'string',
          client_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/sites/:id',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'Get site details with domains, hosting plan, and maintenance info.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          url: 'string|null',
          client_id: 'uuid',
          client: { id: 'uuid', name: 'string' },
          hosted_by: 'string|null',
          platform: 'string|null',
          hosting_plan_id: 'uuid|null',
          hosting_plan: { id: 'uuid', name: 'string', rate: 'number' },
          hosting_discount: 'number|null',
          maintenance_plan_id: 'uuid|null',
          maintenance_plan: { id: 'uuid', name: 'string', rate: 'number', frequency: 'string' },
          maintenance_assignee_id: 'uuid|null',
          maintenance_assignee: { id: 'uuid', name: 'string', email: 'string' },
          notes: 'string|null',
          site_type: 'eleventy|wordpress|handoff|custom|null',
          repo_url: 'string|null',
          repo_branch: 'string|null',
          content_dir: 'string|null',
          prod_branch: 'string|null',
          staging_branch: 'string|null',
          staging_url: 'string|null',
          staging_auth_user: 'string|null',
          staging_auth_password: 'string|null',
          bast_enabled: 'boolean',
          auto_deploy: 'boolean',
          domains_count: 'number',
          domains: [{
            id: 'uuid',
            name: 'string',
            registrar: 'string|null',
            expires_at: 'ISO-8601|null',
            is_primary: 'boolean',
            dns_provider: { id: 'uuid', name: 'string' },
          }],
          primary_domain: 'object|null',
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a site, including Troubador publishing config.',
        auth: 'required',
        roles: ['pm', 'admin'],
        bodySchema: [
          { name: 'name', type: 'string', required: false, description: 'Site name' },
          { name: 'site_type', type: 'string', required: false, description: 'eleventy | wordpress | handoff' },
          { name: 'repo_url', type: 'string', required: false, description: 'Eleventy: git repo URL' },
          { name: 'repo_branch', type: 'string', required: false, description: 'Eleventy: branch' },
          { name: 'content_dir', type: 'string', required: false, description: 'Eleventy: content directory' },
          { name: 'wp_base_url', type: 'string', required: false, description: 'WordPress: REST base URL' },
          { name: 'wp_default_author', type: 'string', required: false, description: 'WordPress: default author (numeric ID)' },
          { name: 'wp_default_category', type: 'string', required: false, description: 'WordPress: default category (numeric ID)' },
          { name: 'handoff_method', type: 'string', required: false, description: 'Handoff: citadel_card | email | drive' },
          { name: 'handoff_recipient', type: 'string', required: false, description: 'Handoff: recipient' },
          { name: 'prod_branch', type: 'string', required: false, description: 'Bast: production deploy branch (else repo_branch is treated as prod)' },
          { name: 'staging_branch', type: 'string', required: false, description: 'Bast: staging deploy branch (default convention: staging)' },
          { name: 'staging_url', type: 'string', required: false, description: 'Bast: staging preview URL (default convention: staging.{primary-domain})' },
          { name: 'staging_auth_user', type: 'string', required: false, description: 'Bast: staging basic-auth user (keeps bots/Google out; not real security)' },
          { name: 'staging_auth_password', type: 'string', required: false, description: 'Bast: staging basic-auth password (stored plain by design)' },
          { name: 'bast_enabled', type: 'boolean', required: false, description: 'Capability gate: Bast is turned on for THIS site (default false). AND-ed with Sop.bast_executable.' },
          { name: 'auto_deploy', type: 'boolean', required: false, description: 'true = Bast pushes straight to prod_branch; false = stage to staging_branch for client approval.' },
        ],
        responseExample: { id: 'uuid', name: 'string', site_type: 'string|null', updated_at: 'ISO-8601' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a site.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/sites/bulk',
    group: 'sites',
    methods: [
      {
        method: 'PATCH',
        summary: 'Bulk update sites.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true, count: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Bulk soft delete sites.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true, count: 'number' },
      },
    ],
  },
  {
    path: '/api/domains',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'List domains with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Filter by site' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          domains: [{
            id: 'uuid',
            name: 'string',
            site_id: 'uuid',
            site: { id: 'uuid', name: 'string', client: { id: 'uuid', name: 'string' } },
            registrar: 'string|null',
            expires_at: 'ISO-8601|null',
            is_primary: 'boolean',
            registered_by: 'string|null',
            dns_provider_id: 'uuid|null',
            dns_provider: { id: 'uuid', name: 'string' },
            dns_managed_by: 'string|null',
            notes: 'string|null',
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
      },
      {
        method: 'POST',
        summary: 'Create a new domain.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', site_id: 'uuid', created_at: 'ISO-8601' },
      },
    ],
  },
  {
    path: '/api/domains/:id',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'Get domain details.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          site_id: 'uuid',
          site: { id: 'uuid', name: 'string', client: { id: 'uuid', name: 'string' } },
          registrar: 'string|null',
          expires_at: 'ISO-8601|null',
          is_primary: 'boolean',
          registered_by: 'string|null',
          dns_provider_id: 'uuid|null',
          dns_provider: { id: 'uuid', name: 'string' },
          dns_managed_by: 'string|null',
          notes: 'string|null',
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a domain.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', updated_at: 'ISO-8601' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a domain.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
];
