import type { ApiEndpoint } from './index';

export const siteEndpoints: ApiEndpoint[] = [
  {
    path: '/api/sites',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'List sites with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Filter by client' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          sites: [{
            id: 'uuid',
            name: 'string',
            url: 'string|null',
            client_id: 'uuid',
            client: { id: 'uuid', name: 'string' },
            hosted_by: 'string|null',
            platform: 'string|null',
            hosting_plan: { id: 'uuid', name: 'string', rate: 'number' },
            hosting_discount: 'number|null',
            maintenance_plan: { id: 'uuid', name: 'string', rate: 'number', frequency: 'string' },
            maintenance_assignee: { id: 'uuid', name: 'string', email: 'string' },
            domains_count: 'number',
            primary_domain: { id: 'uuid', name: 'string', is_primary: true },
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
      },
      {
        method: 'POST',
        summary: 'Create a new site.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: {
          id: 'uuid',
          name: 'string',
          client_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/sites/:id',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'Get site details with domains, hosting plan, and maintenance info.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          url: 'string|null',
          client_id: 'uuid',
          client: { id: 'uuid', name: 'string' },
          hosted_by: 'string|null',
          platform: 'string|null',
          hosting_plan_id: 'uuid|null',
          hosting_plan: { id: 'uuid', name: 'string', rate: 'number' },
          hosting_discount: 'number|null',
          maintenance_plan_id: 'uuid|null',
          maintenance_plan: { id: 'uuid', name: 'string', rate: 'number', frequency: 'string' },
          maintenance_assignee_id: 'uuid|null',
          maintenance_assignee: { id: 'uuid', name: 'string', email: 'string' },
          notes: 'string|null',
          domains_count: 'number',
          domains: [{
            id: 'uuid',
            name: 'string',
            registrar: 'string|null',
            expires_at: 'ISO-8601|null',
            is_primary: 'boolean',
            dns_provider: { id: 'uuid', name: 'string' },
          }],
          primary_domain: 'object|null',
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a site.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', updated_at: 'ISO-8601' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a site.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/sites/bulk',
    group: 'sites',
    methods: [
      {
        method: 'PATCH',
        summary: 'Bulk update sites.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true, count: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Bulk soft delete sites.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true, count: 'number' },
      },
    ],
  },
  {
    path: '/api/domains',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'List domains with pagination, search, and filters.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by name' },
          { name: 'site_id', type: 'uuid', required: false, description: 'Filter by site' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          domains: [{
            id: 'uuid',
            name: 'string',
            site_id: 'uuid',
            site: { id: 'uuid', name: 'string', client: { id: 'uuid', name: 'string' } },
            registrar: 'string|null',
            expires_at: 'ISO-8601|null',
            is_primary: 'boolean',
            registered_by: 'string|null',
            dns_provider_id: 'uuid|null',
            dns_provider: { id: 'uuid', name: 'string' },
            dns_managed_by: 'string|null',
            notes: 'string|null',
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
      },
      {
        method: 'POST',
        summary: 'Create a new domain.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', site_id: 'uuid', created_at: 'ISO-8601' },
      },
    ],
  },
  {
    path: '/api/domains/:id',
    group: 'sites',
    methods: [
      {
        method: 'GET',
        summary: 'Get domain details.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          name: 'string',
          site_id: 'uuid',
          site: { id: 'uuid', name: 'string', client: { id: 'uuid', name: 'string' } },
          registrar: 'string|null',
          expires_at: 'ISO-8601|null',
          is_primary: 'boolean',
          registered_by: 'string|null',
          dns_provider_id: 'uuid|null',
          dns_provider: { id: 'uuid', name: 'string' },
          dns_managed_by: 'string|null',
          notes: 'string|null',
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'PATCH',
        summary: 'Update a domain.',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { id: 'uuid', name: 'string', updated_at: 'ISO-8601' },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a domain.',
        auth: 'required',
        roles: ['admin'],
        responseExample: { success: true },
      },
    ],
  },
];
