import type { ApiEndpoint } from './index';

export const taskEndpoints: ApiEndpoint[] = [
  {
    path: '/api/tasks',
    group: 'tasks',
    methods: [
      {
        method: 'GET',
        summary: 'List tasks with pagination, search, and filters. Tech users only see tasks from visible projects.',
        auth: 'required',
        queryParams: [
          { name: 'search', type: 'string', required: false, description: 'Search by title' },
          { name: 'status', type: 'string', required: false, description: 'Single status filter' },
          { name: 'statuses', type: 'string', required: false, description: 'Comma-separated status list' },
          { name: 'priority', type: 'number', required: false, description: 'Priority filter (1-5)' },
          { name: 'project_id', type: 'uuid', required: false, description: 'Filter by project' },
          { name: 'assignee_id', type: 'uuid', required: false, description: 'Filter by assignee' },
          { name: 'phase', type: 'string', required: false, description: 'Filter by phase' },
          { name: 'my_tasks', type: 'boolean', required: false, description: 'Only tasks assigned to current user' },
          { name: 'pending_review', type: 'boolean', required: false, description: 'Tasks awaiting review approval' },
          { name: 'page', type: 'number', required: false, description: 'Page number' },
          { name: 'limit', type: 'number', required: false, description: 'Items per page' },
        ],
        responseExample: {
          tasks: [{
            id: 'uuid',
            title: 'string',
            description: 'object|null',
            status: 'not_started|in_progress|review|done|blocked|abandoned',
            priority: 'number',
            is_focus: 'boolean',
            project_id: 'uuid|null',
            client_id: 'uuid|null',
            client: { id: 'uuid', name: 'string' },
            project: { id: 'uuid', name: 'string', status: 'string', client: { id: 'uuid', name: 'string' } },
            phase_id: 'uuid|null',
            project_phase: { id: 'uuid', name: 'string', icon: 'string|null', sort_order: 'number' },
            sort_order: 'number',
            assignee_id: 'uuid|null',
            assignee: { id: 'uuid', name: 'string', email: 'string', avatar_url: 'string|null' },
            function_id: 'uuid|null',
            function: { id: 'uuid', name: 'string' },
            energy_estimate: 'number|null',
            mystery_factor: 'none|average|significant|no_idea',
            estimated_minutes: 'number|null',
            battery_impact: 'average_drain|high_drain|energizing',
            due_date: 'ISO-8601|null',
            started_at: 'ISO-8601|null',
            completed_at: 'ISO-8601|null',
            time_spent_minutes: 'number|null',
            needs_review: 'boolean',
            reviewer: { id: 'uuid', name: 'string' },
            approved: 'boolean',
            is_billable: 'boolean',
            invoiced: 'boolean',
            is_deleted: 'boolean',
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
          pagination: { page: 'number', limit: 'number', total: 'number', totalPages: 'number' },
        },
        responseNotes: 'Tech users only see tasks from projects they are assigned to. review_requirements field is only visible to PM/admin roles. time_spent_minutes is calculated from time_entries.',
      },
      {
        method: 'POST',
        summary: 'Create a new task.',
        auth: 'required',
        bodySchema: [
          { name: 'title', type: 'string', required: true, description: 'Task title' },
          { name: 'project_id', type: 'uuid', required: false, description: 'Project ID' },
          { name: 'client_id', type: 'uuid', required: false, description: 'Client ID (derived from project if not set)' },
          { name: 'description', type: 'string', required: false, description: 'Task description' },
          { name: 'status', type: 'string', required: false, description: 'not_started, in_progress, review, done, blocked, abandoned' },
          { name: 'priority', type: 'number', required: false, description: '1 (highest) to 5 (lowest)' },
          { name: 'assignee_id', type: 'uuid', required: false, description: 'Assigned user' },
          { name: 'function_id', type: 'uuid', required: false, description: 'Function/department' },
          { name: 'phase_id', type: 'uuid', required: false, description: 'Project phase' },
          { name: 'energy_estimate', type: 'number', required: false, description: '1-8 energy scale' },
          { name: 'mystery_factor', type: 'string', required: false, description: 'none, average, significant, no_idea' },
          { name: 'battery_impact', type: 'string', required: false, description: 'average_drain, high_drain, energizing' },
          { name: 'due_date', type: 'ISO-8601', required: false, description: 'Due date' },
          { name: 'needs_review', type: 'boolean', required: false, description: 'Whether task needs review' },
          { name: 'reviewer_id', type: 'uuid', required: false, description: 'Reviewer user ID' },
          { name: 'sop_id', type: 'uuid', required: false, description: 'Associated SOP' },
        ],
        responseExample: {
          id: 'uuid',
          title: 'string',
          status: 'string',
          project_id: 'uuid|null',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/tasks/:id',
    group: 'tasks',
    methods: [
      {
        method: 'GET',
        summary: 'Get task detail with project, assignee, time entries, and comments.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          title: 'string',
          description: 'object|null',
          status: 'string',
          priority: 'number',
          is_focus: 'boolean',
          project_id: 'uuid|null',
          client_id: 'uuid|null',
          client: { id: 'uuid', name: 'string' },
          site_id: 'uuid|null',
          site: { id: 'uuid', name: 'string', url: 'string|null' },
          is_maintenance_task: 'boolean',
          maintenance_period: 'string|null',
          time_spent_minutes: 'number|null',
          project: { id: 'uuid', name: 'string', status: 'string', client: { id: 'uuid', name: 'string' } },
          phase_id: 'uuid|null',
          project_phase: { id: 'uuid', name: 'string', icon: 'string|null', sort_order: 'number' },
          sort_order: 'number',
          assignee_id: 'uuid|null',
          assignee: { id: 'uuid', name: 'string', email: 'string', avatar_url: 'string|null' },
          function_id: 'uuid|null',
          function: { id: 'uuid', name: 'string' },
          sop_id: 'uuid|null',
          sop: { id: 'uuid', title: 'string', estimated_minutes: 'number|null', content: 'object|null' },
          energy_estimate: 'number|null',
          mystery_factor: 'string',
          estimated_minutes: 'number|null',
          battery_impact: 'string',
          due_date: 'ISO-8601|null',
          started_at: 'ISO-8601|null',
          completed_at: 'ISO-8601|null',
          requirements: 'string|null',
          review_requirements: 'string|null',
          needs_review: 'boolean',
          reviewer_id: 'uuid|null',
          reviewer: { id: 'uuid', name: 'string', email: 'string', avatar_url: 'string|null' },
          approved: 'boolean',
          approved_at: 'ISO-8601|null',
          approved_by: { id: 'uuid', name: 'string' },
          notes: 'object|null',
          created_by: { id: 'uuid', name: 'string' },
          blocked_by: [{ id: 'uuid', title: 'string', status: 'string' }],
          blocking: [{ id: 'uuid', title: 'string', status: 'string' }],
          time_entries: [{ id: 'uuid', duration: 'number', started_at: 'ISO-8601', description: 'string|null', user: { id: 'uuid', name: 'string' } }],
          is_billable: 'boolean',
          billing_target: 'number|null',
          billing_amount: 'number|null',
          is_retainer_work: 'boolean',
          is_support: 'boolean',
          invoiced: 'boolean',
          invoiced_at: 'ISO-8601|null',
          is_deleted: 'boolean',
          created_at: 'ISO-8601',
          updated_at: 'ISO-8601',
        },
        responseNotes: 'review_requirements is only visible to PM/admin roles and is stripped for tech users. description and notes are stored as JSON (rich text editor format).',
      },
      {
        method: 'PATCH',
        summary: 'Update task fields. Handles status changes, assignment, and focus toggling.',
        auth: 'required',
        responseExample: {
          id: 'uuid',
          title: 'string',
          status: 'string',
          updated_at: 'ISO-8601',
        },
      },
      {
        method: 'DELETE',
        summary: 'Soft delete a task.',
        auth: 'required',
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/tasks/:id/comments',
    group: 'tasks',
    methods: [
      {
        method: 'GET',
        summary: 'List comments on a task.',
        auth: 'required',
        responseExample: {
          comments: [{
            id: 'uuid',
            content: 'string',
            task_id: 'uuid',
            user_id: 'uuid',
            user: { id: 'uuid', name: 'string', avatar_url: 'string|null' },
            created_at: 'ISO-8601',
            updated_at: 'ISO-8601',
          }],
        },
      },
      {
        method: 'POST',
        summary: 'Add a comment to a task.',
        auth: 'required',
        bodySchema: [
          { name: 'content', type: 'string', required: true, description: 'Comment text' },
        ],
        responseExample: {
          id: 'uuid',
          content: 'string',
          task_id: 'uuid',
          user_id: 'uuid',
          created_at: 'ISO-8601',
        },
      },
    ],
  },
  {
    path: '/api/tasks/:id/dependencies',
    group: 'tasks',
    methods: [
      {
        method: 'POST',
        summary: 'Add a task dependency (blocked_by relationship).',
        auth: 'required',
        responseExample: { success: true },
      },
      {
        method: 'DELETE',
        summary: 'Remove a task dependency.',
        auth: 'required',
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/tasks/:id/move',
    group: 'tasks',
    methods: [
      {
        method: 'PATCH',
        summary: 'Move a task to a different phase.',
        auth: 'required',
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/tasks/:id/billing',
    group: 'tasks',
    methods: [
      {
        method: 'PATCH',
        summary: 'Update task billing info (invoiced, billable, billing_target).',
        auth: 'required',
        roles: ['pm', 'admin'],
        responseExample: { success: true },
      },
    ],
  },
  {
    path: '/api/tasks/bulk',
    group: 'tasks',
    methods: [
      {
        method: 'PATCH',
        summary: 'Bulk update tasks (status, assignee, priority, etc).',
        auth: 'required',
        responseExample: { success: true, count: 'number' },
      },
      {
        method: 'DELETE',
        summary: 'Bulk soft delete tasks.',
        auth: 'required',
        responseExample: { success: true, count: 'number' },
      },
    ],
  },
];
