/**
 * Curated list of emojis for use in icon pickers throughout the app.
 * These are commonly used emojis for categorizing and organizing content.
 */

export interface IconOption {
  name: string;
  emoji: string;
  label: string;
  category: string;
}

export const ICON_CATEGORIES = [
  'Objects',
  'Activities',
  'Symbols',
  'Nature',
  'Food',
  'Travel',
  'People',
  'Flags',
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];

export const ICON_OPTIONS: IconOption[] = [
  // Objects
  { name: 'folder', emoji: '📁', label: 'Folder', category: 'Objects' },
  { name: 'file', emoji: '📄', label: 'File', category: 'Objects' },
  { name: 'clipboard', emoji: '📋', label: 'Clipboard', category: 'Objects' },
  { name: 'notebook', emoji: '📓', label: 'Notebook', category: 'Objects' },
  { name: 'book', emoji: '📕', label: 'Book', category: 'Objects' },
  { name: 'books', emoji: '📚', label: 'Books', category: 'Objects' },
  { name: 'bookmark', emoji: '🔖', label: 'Bookmark', category: 'Objects' },
  { name: 'pen', emoji: '🖊️', label: 'Pen', category: 'Objects' },
  { name: 'pencil', emoji: '✏️', label: 'Pencil', category: 'Objects' },
  { name: 'paintbrush', emoji: '🖌️', label: 'Paintbrush', category: 'Objects' },
  { name: 'palette', emoji: '🎨', label: 'Palette', category: 'Objects' },
  { name: 'scissors', emoji: '✂️', label: 'Scissors', category: 'Objects' },
  { name: 'paperclip', emoji: '📎', label: 'Paperclip', category: 'Objects' },
  { name: 'pushpin', emoji: '📌', label: 'Pushpin', category: 'Objects' },
  { name: 'magnet', emoji: '🧲', label: 'Magnet', category: 'Objects' },
  { name: 'lock', emoji: '🔒', label: 'Lock', category: 'Objects' },
  { name: 'key', emoji: '🔑', label: 'Key', category: 'Objects' },
  { name: 'hammer', emoji: '🔨', label: 'Hammer', category: 'Objects' },
  { name: 'wrench', emoji: '🔧', label: 'Wrench', category: 'Objects' },
  { name: 'screwdriver', emoji: '🪛', label: 'Screwdriver', category: 'Objects' },
  { name: 'gear', emoji: '⚙️', label: 'Gear', category: 'Objects' },
  { name: 'link', emoji: '🔗', label: 'Link', category: 'Objects' },
  { name: 'bulb', emoji: '💡', label: 'Light Bulb', category: 'Objects' },
  { name: 'flashlight', emoji: '🔦', label: 'Flashlight', category: 'Objects' },
  { name: 'battery', emoji: '🔋', label: 'Battery', category: 'Objects' },
  { name: 'plug', emoji: '🔌', label: 'Plug', category: 'Objects' },
  { name: 'computer', emoji: '💻', label: 'Computer', category: 'Objects' },
  { name: 'desktop', emoji: '🖥️', label: 'Desktop', category: 'Objects' },
  { name: 'phone', emoji: '📱', label: 'Phone', category: 'Objects' },
  { name: 'camera', emoji: '📷', label: 'Camera', category: 'Objects' },
  { name: 'video', emoji: '📹', label: 'Video', category: 'Objects' },
  { name: 'tv', emoji: '📺', label: 'TV', category: 'Objects' },
  { name: 'microphone', emoji: '🎤', label: 'Microphone', category: 'Objects' },
  { name: 'headphones', emoji: '🎧', label: 'Headphones', category: 'Objects' },
  { name: 'speaker', emoji: '🔊', label: 'Speaker', category: 'Objects' },
  { name: 'bell', emoji: '🔔', label: 'Bell', category: 'Objects' },
  { name: 'megaphone', emoji: '📣', label: 'Megaphone', category: 'Objects' },
  { name: 'mail', emoji: '📧', label: 'Email', category: 'Objects' },
  { name: 'envelope', emoji: '✉️', label: 'Envelope', category: 'Objects' },
  { name: 'package', emoji: '📦', label: 'Package', category: 'Objects' },
  { name: 'gift', emoji: '🎁', label: 'Gift', category: 'Objects' },
  { name: 'shopping', emoji: '🛒', label: 'Shopping Cart', category: 'Objects' },
  { name: 'bag', emoji: '👜', label: 'Bag', category: 'Objects' },
  { name: 'briefcase', emoji: '💼', label: 'Briefcase', category: 'Objects' },
  { name: 'wallet', emoji: '👛', label: 'Wallet', category: 'Objects' },
  { name: 'money', emoji: '💰', label: 'Money Bag', category: 'Objects' },
  { name: 'dollar', emoji: '💵', label: 'Dollar', category: 'Objects' },
  { name: 'credit-card', emoji: '💳', label: 'Credit Card', category: 'Objects' },
  { name: 'chart', emoji: '📊', label: 'Chart', category: 'Objects' },
  { name: 'calendar', emoji: '📅', label: 'Calendar', category: 'Objects' },
  { name: 'clock', emoji: '🕐', label: 'Clock', category: 'Objects' },
  { name: 'hourglass', emoji: '⏳', label: 'Hourglass', category: 'Objects' },
  { name: 'stopwatch', emoji: '⏱️', label: 'Stopwatch', category: 'Objects' },
  { name: 'alarm', emoji: '⏰', label: 'Alarm', category: 'Objects' },
  { name: 'magnifier', emoji: '🔍', label: 'Magnifier', category: 'Objects' },
  { name: 'microscope', emoji: '🔬', label: 'Microscope', category: 'Objects' },
  { name: 'telescope', emoji: '🔭', label: 'Telescope', category: 'Objects' },
  { name: 'test-tube', emoji: '🧪', label: 'Test Tube', category: 'Objects' },
  { name: 'pill', emoji: '💊', label: 'Pill', category: 'Objects' },
  { name: 'syringe', emoji: '💉', label: 'Syringe', category: 'Objects' },
  { name: 'dna', emoji: '🧬', label: 'DNA', category: 'Objects' },
  { name: 'bone', emoji: '🦴', label: 'Bone', category: 'Objects' },

  // Activities
  { name: 'target', emoji: '🎯', label: 'Target', category: 'Activities' },
  { name: 'trophy', emoji: '🏆', label: 'Trophy', category: 'Activities' },
  { name: 'medal', emoji: '🏅', label: 'Medal', category: 'Activities' },
  { name: 'ribbon', emoji: '🎀', label: 'Ribbon', category: 'Activities' },
  { name: 'ticket', emoji: '🎟️', label: 'Ticket', category: 'Activities' },
  { name: 'balloon', emoji: '🎈', label: 'Balloon', category: 'Activities' },
  { name: 'party', emoji: '🎉', label: 'Party', category: 'Activities' },
  { name: 'confetti', emoji: '🎊', label: 'Confetti', category: 'Activities' },
  { name: 'sparkles', emoji: '✨', label: 'Sparkles', category: 'Activities' },
  { name: 'star', emoji: '⭐', label: 'Star', category: 'Activities' },
  { name: 'star2', emoji: '🌟', label: 'Glowing Star', category: 'Activities' },
  { name: 'fire', emoji: '🔥', label: 'Fire', category: 'Activities' },
  { name: 'lightning', emoji: '⚡', label: 'Lightning', category: 'Activities' },
  { name: 'boom', emoji: '💥', label: 'Boom', category: 'Activities' },
  { name: 'rocket', emoji: '🚀', label: 'Rocket', category: 'Activities' },
  { name: 'airplane', emoji: '✈️', label: 'Airplane', category: 'Activities' },
  { name: 'game', emoji: '🎮', label: 'Game', category: 'Activities' },
  { name: 'dice', emoji: '🎲', label: 'Dice', category: 'Activities' },
  { name: 'puzzle', emoji: '🧩', label: 'Puzzle', category: 'Activities' },
  { name: 'art', emoji: '🖼️', label: 'Art', category: 'Activities' },
  { name: 'music', emoji: '🎵', label: 'Music', category: 'Activities' },
  { name: 'guitar', emoji: '🎸', label: 'Guitar', category: 'Activities' },
  { name: 'drum', emoji: '🥁', label: 'Drum', category: 'Activities' },
  { name: 'soccer', emoji: '⚽', label: 'Soccer', category: 'Activities' },
  { name: 'basketball', emoji: '🏀', label: 'Basketball', category: 'Activities' },
  { name: 'football', emoji: '🏈', label: 'Football', category: 'Activities' },
  { name: 'tennis', emoji: '🎾', label: 'Tennis', category: 'Activities' },
  { name: 'bowling', emoji: '🎳', label: 'Bowling', category: 'Activities' },
  { name: 'fitness', emoji: '💪', label: 'Fitness', category: 'Activities' },
  { name: 'running', emoji: '🏃', label: 'Running', category: 'Activities' },
  { name: 'biking', emoji: '🚴', label: 'Biking', category: 'Activities' },
  { name: 'swimming', emoji: '🏊', label: 'Swimming', category: 'Activities' },

  // Symbols
  { name: 'check', emoji: '✅', label: 'Check', category: 'Symbols' },
  { name: 'checkmark', emoji: '✔️', label: 'Checkmark', category: 'Symbols' },
  { name: 'x', emoji: '❌', label: 'X', category: 'Symbols' },
  { name: 'plus', emoji: '➕', label: 'Plus', category: 'Symbols' },
  { name: 'minus', emoji: '➖', label: 'Minus', category: 'Symbols' },
  { name: 'question', emoji: '❓', label: 'Question', category: 'Symbols' },
  { name: 'exclamation', emoji: '❗', label: 'Exclamation', category: 'Symbols' },
  { name: 'warning', emoji: '⚠️', label: 'Warning', category: 'Symbols' },
  { name: 'info', emoji: 'ℹ️', label: 'Info', category: 'Symbols' },
  { name: 'prohibited', emoji: '🚫', label: 'Prohibited', category: 'Symbols' },
  { name: 'stop', emoji: '🛑', label: 'Stop', category: 'Symbols' },
  { name: 'heart', emoji: '❤️', label: 'Heart', category: 'Symbols' },
  { name: 'orange-heart', emoji: '🧡', label: 'Orange Heart', category: 'Symbols' },
  { name: 'yellow-heart', emoji: '💛', label: 'Yellow Heart', category: 'Symbols' },
  { name: 'green-heart', emoji: '💚', label: 'Green Heart', category: 'Symbols' },
  { name: 'blue-heart', emoji: '💙', label: 'Blue Heart', category: 'Symbols' },
  { name: 'purple-heart', emoji: '💜', label: 'Purple Heart', category: 'Symbols' },
  { name: 'thumbs-up', emoji: '👍', label: 'Thumbs Up', category: 'Symbols' },
  { name: 'thumbs-down', emoji: '👎', label: 'Thumbs Down', category: 'Symbols' },
  { name: 'clap', emoji: '👏', label: 'Clap', category: 'Symbols' },
  { name: 'handshake', emoji: '🤝', label: 'Handshake', category: 'Symbols' },
  { name: 'pray', emoji: '🙏', label: 'Pray', category: 'Symbols' },
  { name: 'point-right', emoji: '👉', label: 'Point Right', category: 'Symbols' },
  { name: 'point-up', emoji: '👆', label: 'Point Up', category: 'Symbols' },
  { name: 'eyes', emoji: '👀', label: 'Eyes', category: 'Symbols' },
  { name: 'brain', emoji: '🧠', label: 'Brain', category: 'Symbols' },
  { name: 'speech', emoji: '💬', label: 'Speech', category: 'Symbols' },
  { name: 'thought', emoji: '💭', label: 'Thought', category: 'Symbols' },
  { name: 'zzz', emoji: '💤', label: 'Sleep', category: 'Symbols' },
  { name: 'hundred', emoji: '💯', label: '100', category: 'Symbols' },
  { name: 'recycle', emoji: '♻️', label: 'Recycle', category: 'Symbols' },
  { name: 'infinity', emoji: '♾️', label: 'Infinity', category: 'Symbols' },

  // Nature
  { name: 'sun', emoji: '☀️', label: 'Sun', category: 'Nature' },
  { name: 'moon', emoji: '🌙', label: 'Moon', category: 'Nature' },
  { name: 'star-night', emoji: '🌠', label: 'Shooting Star', category: 'Nature' },
  { name: 'cloud', emoji: '☁️', label: 'Cloud', category: 'Nature' },
  { name: 'rain', emoji: '🌧️', label: 'Rain', category: 'Nature' },
  { name: 'snow', emoji: '❄️', label: 'Snow', category: 'Nature' },
  { name: 'rainbow', emoji: '🌈', label: 'Rainbow', category: 'Nature' },
  { name: 'tornado', emoji: '🌪️', label: 'Tornado', category: 'Nature' },
  { name: 'wave', emoji: '🌊', label: 'Wave', category: 'Nature' },
  { name: 'droplet', emoji: '💧', label: 'Droplet', category: 'Nature' },
  { name: 'flame', emoji: '🔥', label: 'Flame', category: 'Nature' },
  { name: 'earth', emoji: '🌍', label: 'Earth', category: 'Nature' },
  { name: 'globe', emoji: '🌐', label: 'Globe', category: 'Nature' },
  { name: 'mountain', emoji: '⛰️', label: 'Mountain', category: 'Nature' },
  { name: 'volcano', emoji: '🌋', label: 'Volcano', category: 'Nature' },
  { name: 'tree', emoji: '🌳', label: 'Tree', category: 'Nature' },
  { name: 'palm', emoji: '🌴', label: 'Palm', category: 'Nature' },
  { name: 'cactus', emoji: '🌵', label: 'Cactus', category: 'Nature' },
  { name: 'plant', emoji: '🌱', label: 'Seedling', category: 'Nature' },
  { name: 'herb', emoji: '🌿', label: 'Herb', category: 'Nature' },
  { name: 'leaf', emoji: '🍃', label: 'Leaf', category: 'Nature' },
  { name: 'maple', emoji: '🍁', label: 'Maple Leaf', category: 'Nature' },
  { name: 'flower', emoji: '🌸', label: 'Flower', category: 'Nature' },
  { name: 'sunflower', emoji: '🌻', label: 'Sunflower', category: 'Nature' },
  { name: 'rose', emoji: '🌹', label: 'Rose', category: 'Nature' },
  { name: 'tulip', emoji: '🌷', label: 'Tulip', category: 'Nature' },
  { name: 'mushroom', emoji: '🍄', label: 'Mushroom', category: 'Nature' },
  { name: 'bug', emoji: '🐛', label: 'Bug', category: 'Nature' },
  { name: 'butterfly', emoji: '🦋', label: 'Butterfly', category: 'Nature' },
  { name: 'bee', emoji: '🐝', label: 'Bee', category: 'Nature' },
  { name: 'ladybug', emoji: '🐞', label: 'Ladybug', category: 'Nature' },
  { name: 'dog', emoji: '🐕', label: 'Dog', category: 'Nature' },
  { name: 'cat', emoji: '🐈', label: 'Cat', category: 'Nature' },
  { name: 'rabbit', emoji: '🐇', label: 'Rabbit', category: 'Nature' },
  { name: 'fox', emoji: '🦊', label: 'Fox', category: 'Nature' },
  { name: 'bear', emoji: '🐻', label: 'Bear', category: 'Nature' },
  { name: 'panda', emoji: '🐼', label: 'Panda', category: 'Nature' },
  { name: 'unicorn', emoji: '🦄', label: 'Unicorn', category: 'Nature' },
  { name: 'dragon', emoji: '🐉', label: 'Dragon', category: 'Nature' },

  // Food
  { name: 'apple', emoji: '🍎', label: 'Apple', category: 'Food' },
  { name: 'orange', emoji: '🍊', label: 'Orange', category: 'Food' },
  { name: 'lemon', emoji: '🍋', label: 'Lemon', category: 'Food' },
  { name: 'banana', emoji: '🍌', label: 'Banana', category: 'Food' },
  { name: 'watermelon', emoji: '🍉', label: 'Watermelon', category: 'Food' },
  { name: 'grapes', emoji: '🍇', label: 'Grapes', category: 'Food' },
  { name: 'strawberry', emoji: '🍓', label: 'Strawberry', category: 'Food' },
  { name: 'cherry', emoji: '🍒', label: 'Cherry', category: 'Food' },
  { name: 'peach', emoji: '🍑', label: 'Peach', category: 'Food' },
  { name: 'avocado', emoji: '🥑', label: 'Avocado', category: 'Food' },
  { name: 'carrot', emoji: '🥕', label: 'Carrot', category: 'Food' },
  { name: 'corn', emoji: '🌽', label: 'Corn', category: 'Food' },
  { name: 'pepper', emoji: '🌶️', label: 'Pepper', category: 'Food' },
  { name: 'broccoli', emoji: '🥦', label: 'Broccoli', category: 'Food' },
  { name: 'bread', emoji: '🍞', label: 'Bread', category: 'Food' },
  { name: 'croissant', emoji: '🥐', label: 'Croissant', category: 'Food' },
  { name: 'cheese', emoji: '🧀', label: 'Cheese', category: 'Food' },
  { name: 'egg', emoji: '🥚', label: 'Egg', category: 'Food' },
  { name: 'bacon', emoji: '🥓', label: 'Bacon', category: 'Food' },
  { name: 'burger', emoji: '🍔', label: 'Burger', category: 'Food' },
  { name: 'pizza', emoji: '🍕', label: 'Pizza', category: 'Food' },
  { name: 'hotdog', emoji: '🌭', label: 'Hotdog', category: 'Food' },
  { name: 'taco', emoji: '🌮', label: 'Taco', category: 'Food' },
  { name: 'burrito', emoji: '🌯', label: 'Burrito', category: 'Food' },
  { name: 'sushi', emoji: '🍣', label: 'Sushi', category: 'Food' },
  { name: 'ramen', emoji: '🍜', label: 'Ramen', category: 'Food' },
  { name: 'rice', emoji: '🍚', label: 'Rice', category: 'Food' },
  { name: 'curry', emoji: '🍛', label: 'Curry', category: 'Food' },
  { name: 'cake', emoji: '🎂', label: 'Cake', category: 'Food' },
  { name: 'cookie', emoji: '🍪', label: 'Cookie', category: 'Food' },
  { name: 'donut', emoji: '🍩', label: 'Donut', category: 'Food' },
  { name: 'icecream', emoji: '🍦', label: 'Ice Cream', category: 'Food' },
  { name: 'chocolate', emoji: '🍫', label: 'Chocolate', category: 'Food' },
  { name: 'candy', emoji: '🍬', label: 'Candy', category: 'Food' },
  { name: 'coffee', emoji: '☕', label: 'Coffee', category: 'Food' },
  { name: 'tea', emoji: '🍵', label: 'Tea', category: 'Food' },
  { name: 'beer', emoji: '🍺', label: 'Beer', category: 'Food' },
  { name: 'wine', emoji: '🍷', label: 'Wine', category: 'Food' },
  { name: 'cocktail', emoji: '🍸', label: 'Cocktail', category: 'Food' },

  // Travel
  { name: 'car', emoji: '🚗', label: 'Car', category: 'Travel' },
  { name: 'taxi', emoji: '🚕', label: 'Taxi', category: 'Travel' },
  { name: 'bus', emoji: '🚌', label: 'Bus', category: 'Travel' },
  { name: 'truck', emoji: '🚚', label: 'Truck', category: 'Travel' },
  { name: 'bike', emoji: '🚲', label: 'Bike', category: 'Travel' },
  { name: 'motorcycle', emoji: '🏍️', label: 'Motorcycle', category: 'Travel' },
  { name: 'train', emoji: '🚂', label: 'Train', category: 'Travel' },
  { name: 'metro', emoji: '🚇', label: 'Metro', category: 'Travel' },
  { name: 'ship', emoji: '🚢', label: 'Ship', category: 'Travel' },
  { name: 'sailboat', emoji: '⛵', label: 'Sailboat', category: 'Travel' },
  { name: 'helicopter', emoji: '🚁', label: 'Helicopter', category: 'Travel' },
  { name: 'house', emoji: '🏠', label: 'House', category: 'Travel' },
  { name: 'building', emoji: '🏢', label: 'Building', category: 'Travel' },
  { name: 'office', emoji: '🏬', label: 'Office', category: 'Travel' },
  { name: 'hospital', emoji: '🏥', label: 'Hospital', category: 'Travel' },
  { name: 'school', emoji: '🏫', label: 'School', category: 'Travel' },
  { name: 'bank', emoji: '🏦', label: 'Bank', category: 'Travel' },
  { name: 'hotel', emoji: '🏨', label: 'Hotel', category: 'Travel' },
  { name: 'church', emoji: '⛪', label: 'Church', category: 'Travel' },
  { name: 'castle', emoji: '🏰', label: 'Castle', category: 'Travel' },
  { name: 'factory', emoji: '🏭', label: 'Factory', category: 'Travel' },
  { name: 'stadium', emoji: '🏟️', label: 'Stadium', category: 'Travel' },
  { name: 'tent', emoji: '⛺', label: 'Tent', category: 'Travel' },
  { name: 'compass', emoji: '🧭', label: 'Compass', category: 'Travel' },
  { name: 'map', emoji: '🗺️', label: 'Map', category: 'Travel' },
  { name: 'pin', emoji: '📍', label: 'Pin', category: 'Travel' },
  { name: 'flag', emoji: '🚩', label: 'Flag', category: 'Travel' },

  // People
  { name: 'person', emoji: '👤', label: 'Person', category: 'People' },
  { name: 'people', emoji: '👥', label: 'People', category: 'People' },
  { name: 'baby', emoji: '👶', label: 'Baby', category: 'People' },
  { name: 'child', emoji: '🧒', label: 'Child', category: 'People' },
  { name: 'adult', emoji: '🧑', label: 'Adult', category: 'People' },
  { name: 'man', emoji: '👨', label: 'Man', category: 'People' },
  { name: 'woman', emoji: '👩', label: 'Woman', category: 'People' },
  { name: 'elder', emoji: '🧓', label: 'Elder', category: 'People' },
  { name: 'doctor', emoji: '👨‍⚕️', label: 'Doctor', category: 'People' },
  { name: 'student', emoji: '👨‍🎓', label: 'Student', category: 'People' },
  { name: 'teacher', emoji: '👨‍🏫', label: 'Teacher', category: 'People' },
  { name: 'scientist', emoji: '👨‍🔬', label: 'Scientist', category: 'People' },
  { name: 'artist', emoji: '👨‍🎨', label: 'Artist', category: 'People' },
  { name: 'chef', emoji: '👨‍🍳', label: 'Chef', category: 'People' },
  { name: 'mechanic', emoji: '👨‍🔧', label: 'Mechanic', category: 'People' },
  { name: 'farmer', emoji: '👨‍🌾', label: 'Farmer', category: 'People' },
  { name: 'pilot', emoji: '👨‍✈️', label: 'Pilot', category: 'People' },
  { name: 'astronaut', emoji: '👨‍🚀', label: 'Astronaut', category: 'People' },
  { name: 'detective', emoji: '🕵️', label: 'Detective', category: 'People' },
  { name: 'guard', emoji: '💂', label: 'Guard', category: 'People' },
  { name: 'ninja', emoji: '🥷', label: 'Ninja', category: 'People' },
  { name: 'superhero', emoji: '🦸', label: 'Superhero', category: 'People' },
  { name: 'zombie', emoji: '🧟', label: 'Zombie', category: 'People' },
  { name: 'robot', emoji: '🤖', label: 'Robot', category: 'People' },
  { name: 'alien', emoji: '👽', label: 'Alien', category: 'People' },
  { name: 'ghost', emoji: '👻', label: 'Ghost', category: 'People' },
  { name: 'skull', emoji: '💀', label: 'Skull', category: 'People' },

  // Flags
  { name: 'flag-white', emoji: '🏳️', label: 'White Flag', category: 'Flags' },
  { name: 'flag-black', emoji: '🏴', label: 'Black Flag', category: 'Flags' },
  { name: 'flag-checkered', emoji: '🏁', label: 'Checkered Flag', category: 'Flags' },
  { name: 'flag-triangular', emoji: '🚩', label: 'Triangular Flag', category: 'Flags' },
  { name: 'flag-crossed', emoji: '🎌', label: 'Crossed Flags', category: 'Flags' },
];

/**
 * Get an icon option by name
 */
export function getIconOption(name: string): IconOption | undefined {
  return ICON_OPTIONS.find((opt) => opt.name === name);
}

/**
 * Get icons by category
 */
export function getIconsByCategory(category: IconCategory): IconOption[] {
  return ICON_OPTIONS.filter((opt) => opt.category === category);
}

/**
 * Default icon for sections
 */
export const DEFAULT_SECTION_ICON = 'folder';
